version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:3.1.0
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    environment:
      - PREFIX_PULSAR_webSocketServiceEnabled=true
    command: bin/pulsar standalone

volumes:
  pulsardata:
  pulsarconf:

